# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GIMNRec.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from random import choice

window_titles = [
    'My App',
    'My App',
    'Still My App',
    'Still My App',
    'What on earth',
    'What on earth',
    'This is surprising',
    'This is surprising',
    'Something went wrong'
]

class Ui_GIMNRec(object):
    def setupUi(self, GIMNRec):
        print(self)
        GIMNRec.setObjectName("GIMNRec")
        GIMNRec.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(GIMNRec)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-130, 0, 791, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.toolButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout.addWidget(self.toolButton)
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.verticalLayoutWidget)
        self.openGLWidget.setObjectName("openGLWidget")
        self.verticalLayout.addWidget(self.openGLWidget)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setObjectName('pushbutton2')
        self.pushButton2.setText('Outro push button')
        self.pushButton2.clicked.connect(self.openDialog)
        self.verticalLayout.addWidget(self.pushButton)
        GIMNRec.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GIMNRec)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        GIMNRec.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GIMNRec)
        self.statusbar.setObjectName("statusbar")


        GIMNRec.setStatusBar(self.statusbar)
        

        self.retranslateUi(GIMNRec)
        QtCore.QMetaObject.connectSlotsByName(GIMNRec)

    def openDialog(self):
        fname = QtWidgets.QFileDialog.getOpenFileName(self,"Oepn File", "", "All files(*)")
        print(fname)

    def the_window_title_changed(self, window_title):
        print("Window title changed: %s" % window_title)
        print(self)
        if window_title == 'Something went wrong':
            self.button.setDisabled(True)
    
    
    def retranslateUi(self, GIMNRec):
        _translate = QtCore.QCoreApplication.translate
        GIMNRec.setWindowTitle(_translate("GIMNRec", "Oie"))
        self.toolButton.setText(_translate("GIMNRec", "..."))
        self.pushButton.setText(_translate("GIMNRec", "PushButton"))
